language: nodejs
sudo: false

before_install:
- nvm install 8
- node --version

install:
- npm install

script:
  - npm test
  # - if [[ "$NODE_VERSION" = 7 ]]; then sh upload.sh; fi

after_success:
  - sh build.sh

notifications:
  email:
    recipients:
      - priyanshujindal1995@gmail.com
    on_failure: change
    on_success: change
