// flow-typed signature: c016b71ac5ae13389b2ec93c1865843a
// flow-typed version: <<STUB>>/next-frame_v^0.2.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-frame' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-frame/index' {
  declare module.exports: $Exports<'next-frame'>;
}
declare module 'next-frame/index.js' {
  declare module.exports: $Exports<'next-frame'>;
}
